### Crie um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possiceis sobre ele.
n = str(input('Digite algo: '))
print(type(n))
print(n.isupper())
print(n.istitle())
print(n.isspace())
print(n.isprintable())
print('Apenas um teste',n.isnumeric())
print(n.islower())
print(n.isidentifier())
print(n.isdigit())
print(n.isdecimal())
print(n.isascii())
print(n.isalpha())
